frontend:
  service:
    port: 80
    type: ClusterIP
  image:
    repository: cr.yandex/crplvdacg3tpu0lg6jj7/givegift-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1

backend:
  service:
    port: 5000
    type: ClusterIP
  image:
    repository: cr.yandex/crplvdacg3tpu0lg6jj7/givegift-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount:
    min: 1
    max: 5
  cpuAverageUtilization: 15

db:
  localCertPath: C:/Users/AmEl/Downloads/cacert.pem
