apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: givegift-argocd-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      frontend=cr.yandex/crplvdacg3tpu0lg6jj7/givegift-frontend:latest,
      backend=cr.yandex/crplvdacg3tpu0lg6jj7/givegift-backend:latest

    argocd-image-updater.argoproj.io/frontend.update-strategy: "latest"
    argocd-image-updater.argoproj.io/backend.update-strategy: "latest"
    argocd-image-updater.argoproj.io/pull-policy: Always
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Amirelkanov/givegift-argocd
    targetRevision: main
    path: givegift/
  destination:
    server: https://kubernetes.default.svc
    namespace: givegift-argocd-app-ns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
