apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: givegift-argocd-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      frontend=cr.yandex/crplvdacg3tpu0lg6jj7/givegift-frontend:latest,
      backend=cr.yandex/crplvdacg3tpu0lg6jj7/givegift-backend:latest

    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build

    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/yandex-creds
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:argocd/yandex-creds

    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:values.yaml"

    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag

spec:
  project: default
  source:
    repoURL: https://github.com/Amirelkanov/givegift-argocd
    targetRevision: main
    path: givegift/
  destination:
    server: https://kubernetes.default.svc
    namespace: givegift-argocd-app-ns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
